name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1 # could be a branch name, release or specific hash commit
        with:
          who-to-greet: Jhonathan
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"  # github provide  this steps variable