name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string # this is not required
        run: echo "Hello World!" # bash command (ubuntu)
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: echo ubuntu version
        run: cat /etc/issue
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-cmd-windows:
    runs-on: windows-latest
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash